#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Genera la animación del zoom infinito en cada idioma a partir de la castellana (ADR 20).

Uso, desde la raíz del repositorio: python3 animacion/traducir.py [idioma…]
zoom.es.html es el original y el único que se edita; este script escribe zoom.<idioma>.html
sustituyendo cada texto por su traducción. Cada texto castellano debe aparecer en el original:
si se cambia allí, hay que cambiarlo también aquí, y el script avisa del que ya no encuentra.
Las claves llevan el contexto necesario para no confundir un texto con otro igual (por ejemplo,
«La IA» suelto y «La IA puede equivocarse…»). Después, cada página se graba con
node animacion/grabar.js <idioma> zoom.
"""
import sys
from pathlib import Path

AQUI = Path(__file__).parent

# Lo que cambia igual en todos los idiomas: el atributo de idioma, la portada a la que vuelve
# la cabecera y la licencia en el idioma de la página.
def comunes(i):
    return [('<html lang="es">', f'<html lang="{i}">'),
            ('href="../es/index.html"', f'href="../{i}/index.html"'),
            ('by-sa/4.0/deed.es"', f'by-sa/4.0/deed.{i}"')]

TEXTOS = {
    "en": [
        ("Vibe coding responsable · Zoom infinito", "Responsible vibe coding · Infinite zoom"),
        ('content="Animación de la guía «Vibe coding responsable» en un solo plano: un zoom infinito que entra en el cursor de una conversación con la IA y recorre las diez recomendaciones en cuatro mundos, uno dentro de otro."',
         'content="Animation of the guide «Responsible vibe coding» in a single shot: an infinite zoom that enters the cursor of a conversation with the AI and goes through the ten recommendations in four worlds, one inside another."'),
        ('alt="">Vibe coding responsable</a>', 'alt="">Responsible vibe coding</a>'),
        ("<span>· Zoom infinito</span>", "<span>· Infinite zoom</span>"),
        ("<h1>La guía en un zoom infinito</h1>", "<h1>The guide in an infinite zoom</h1>"),
        ('aria-label="Animación en un solo plano sobre la guía Vibe coding responsable."', 'aria-label="Single-shot animation about the guide Responsible vibe coding."'),
        ("Reproducir con sonido</button>", "Play with sound</button>"),
        ('"Parte anterior"', '"Previous part"'),
        ('aria-label="Reproducir" title="Reproducir (barra espaciadora)"', 'aria-label="Play" title="Play (space bar)"'),
        ('"Parte siguiente"', '"Next part"'),
        ('aria-label="Posición en la animación"', 'aria-label="Position in the animation"'),
        ('aria-label="Silenciar" title="Silenciar"', 'aria-label="Mute" title="Mute"'),
        (". Contenido: <a", ". Content: <a"),
        ('<span>Creada con IA (<a href="https://jjdeharo.github.io/miae/?nivel=4" target="_blank" rel="noopener">nivel 4 del MIAE</a>): el autor ha dirigido el trabajo y ha contrastado los textos con la guía.</span>',
         '<span>Created with AI (<a href="https://jjdeharo.github.io/miae/?nivel=4" target="_blank" rel="noopener">MIAE level 4</a>): the author directed the work and checked the texts against the guide.</span>'),
        ('"› crea una simulación del ciclo del agua"', '"› create a simulation of the water cycle"'),
        ('"VIBE CODING EDUCATIVO"', '"EDUCATIONAL VIBE CODING"'),
        ('"La IA", A(4.1', '"The AI", A(4.1'),
        ('"escribe el código."', '"writes the code."'),
        ('"La persona", A(7.0', '"The person", A(7.0'),
        ('"aporta la intención pedagógica"', '"brings the teaching intention"'),
        ('"y comprueba el resultado."', '"and checks the result."'),
        ('"Quien publica el material responde de él,"', '"Whoever publishes the material answers for it,"'),
        ('"aunque el código sea de la IA."', '"even if the AI wrote the code."'),
        ('"recomendaciones", A(12.9', '"recommendations", A(12.9'),
        ('"antes de publicar"', '"before publishing"'),
        ('"Vibe coding", A(109.1', '"Responsible", A(109.1'),
        ('"responsable", A(109.45', '"vibe coding", A(109.45'),
        ('"Vibe coding ético"', '"Ethical vibe coding"'),
        ('"Vibe coding educativo responsable: materiales…"', '"Responsible educational vibe coding: materials…"'),
        ('[["seguros", "para el alumnado,"], ["accesibles,", ""], ["duraderos,", ""], ["transparentes", "sobre cómo se hicieron"], ["y libres", "para que otras personas los reutilicen."]]',
         '[["safe", "for students,"], ["accessible,", ""], ["durable,", ""], ["transparent", "about how they were made"], ["and free", "for others to reuse."]]'),
        ("Para empezar:</b> dar a la IA el archivo de instrucciones y, al terminar, pedirle la evaluación VCER. La revisión del contenido corresponde a la persona.",
         "To start:</b> give the AI the instructions file and, when finished, ask it for the VCER evaluation. Reviewing the content is the person's job."),
        ("Iconos: Lucide (ISC y MIT) · Tipografía: Atkinson Hyperlegible (OFL)<br>Animación, música y sonido generados con IA.",
         "Icons: Lucide (ISC and MIT) · Typeface: Atkinson Hyperlegible (OFL)<br>Animation, music and sound generated with AI."),
        ('fase(N1, 1, "Proteger", "al alumnado"', 'fase(N1, 1, "Protect", "students"'),
        ('fase(N2, 2, "Construir", "el material"', 'fase(N2, 2, "Build", "the material"'),
        ('fase(N3, 3, "Documentar", "el trabajo"', 'fase(N3, 3, "Document", "the work"'),
        ('fase(N4, 4, "Compartir", "el material"', 'fase(N4, 4, "Share", "the material"'),
        ("`FASE ${numero} DE 4`", "`PHASE ${numero} OF 4`"),
        ('"Revisar el contenido sin delegarlo en la IA"', '"Review the content without delegating it to the AI"'),
        ('"No enviar datos personales a servicios ajenos al centro"', '"Do not send personal data to services outside the school"'),
        ('"Entender qué hace el material"', '"Understand what the material does"'),
        ('"No depender de servicios que pueden desaparecer"', '"Do not depend on services that may disappear"'),
        ('"Hacerlo accesible a cualquier persona"', '"Make it accessible to everyone"'),
        ('"Citar la autoría de lo que se toma de otras personas"', '"Credit the authorship of what is taken from others"'),
        ('"Guardar el rastro de cómo se hizo"', '"Keep a record of how it was made"'),
        ('"Declarar el uso de IA y lo que se ha comprobado"', '"Declare the use of AI and what has been checked"'),
        ('"Publicar con una licencia libre a la vista"', '"Publish with a visible free licence"'),
        ('"Ofrecer el código para que otras personas lo adapten"', '"Offer the code so that others can adapt it"'),
        (">PREGUNTA DEL CUESTIONARIO<", ">QUIZ QUESTION<"),
        (">El agua hierve a 90 °C a nivel del mar.<", ">Water boils at 90 °C at sea level.<"),
        ("} Verdadero`", "} True`"),
        ("} Error`", "} Wrong`"),
        ('"La IA puede equivocarse con total naturalidad."', '"AI can make mistakes very naturally."'),
        ('"La responsabilidad de lo que se enseña es de la persona que lo publica."', '"Responsibility for what is taught lies with the person who publishes it."'),
        ('"La forma más sencilla de cumplir: que el material no pida datos."', '"The simplest way to comply: the material asks for no data."'),
        ("<p>servicio ajeno al centro</p>", "<p>service outside the school</p>"),
        ('"Los datos, solo en el dispositivo."', '"Data stay on the device."'),
        ('["nombre", "notas", "voz", "imagen"]', '["name", "marks", "voice", "image"]'),
        ("</span> comprobar(respuesta) {", "</span> check(answer) {"),
        ("</span> bien = respuesta === solucion;", "</span> ok = answer === solution;"),
        ('mostrar(bien ? <span style="color:#f5c542">"¡Correcto!"</span> : <span style="color:#f5c542">"Revisa"</span>);',
         'show(ok ? <span style="color:#f5c542">"Correct!"</span> : <span style="color:#f5c542">"Try again"</span>);'),
        ('"progreso"</span>, nivel);', '"progress"</span>, level);'),
        ("// sin conexiones a servidores externos", "// no connections to external servers"),
        ('[["Qué hace", "comprueba las respuestas", 3.9, 452], ["Qué guarda", "el progreso, en el dispositivo", 4.5, 572], ["Con qué se comunica", "con ningún servidor externo", 5.1, 692]]',
         '[["What it does", "checks the answers", 3.9, 452], ["What it stores", "progress, on the device", 4.5, 572], ["What it talks to", "no external server", 5.1, 692]]'),
        ('"No hace falta saber programar: basta con pedir a la IA que lo explique en lenguaje llano y comprobarlo al usarlo."',
         '"No need to know how to program: just ask the AI to explain it in plain language and check it when using it."'),
        (">la plataforma donde se creó<", ">the platform where it was made<"),
        ("} enlace compartido`", "} shared link`"),
        ("} enlace roto`", "} broken link`"),
        ('"copia del código"', '"copy of the code"'),
        ('"El enlace compartido dura lo que la empresa decida."', '"The shared link lasts as long as the company decides."'),
        ('"Por eso, una copia del código en el propio ordenador."', '"Hence, a copy of the code on your own computer."'),
        (">sin ratón<", ">no mouse<"),
        ("} Correcto</div>", "} Correct</div>"),
        ("} Error</div>", "} Wrong</div>"),
        (">sin depender del color<", ">without relying on colour<"),
        (">Ciclo del agua</b><br>Evaporación, condensación y precipitación.<", ">Water cycle</b><br>Evaporation, condensation and precipitation.<"),
        (">en una pantalla pequeña<", ">on a small screen<"),
        ('"Pedir a la IA, desde el principio, que siga las pautas de accesibilidad."', '"Ask the AI, from the start, to follow the accessibility guidelines."'),
        ('[["imagen", "imagen"], ["musica", "sonido"], [null, "tipografía"]]', '[["imagen", "image"], ["musica", "sound"], [null, "typeface"]]'),
        ('"<b>Autoría</b><br><b>Procedencia</b><br><b>Licencia</b>"', '"<b>Author</b><br><b>Source</b><br><b>Licence</b>"'),
        ('"Tienen autoría y licencia, aunque los haya colocado la IA."', '"They have authors and licences, even if the AI placed them."'),
        ('[["Los datos se guardan solo en el dispositivo.", "Porque son datos del alumnado."],\n ["Iconos de una biblioteca con licencia libre.", "Porque se pueden reutilizar y citar."],\n ["Sin cuentas de usuario.", "Porque así el alumnado no tiene que registrarse."]]',
         '[["Data are stored only on the device.", "Because they are students\' data."],\n ["Icons from a library with a free licence.", "Because they can be reused and credited."],\n ["No user accounts.", "So that students do not have to register."]]'),
        ('"Lo redacta la propia IA al terminar cada sesión; la persona lo revisa."', '"The AI itself writes it at the end of each session; the person reviews it."'),
        ('"Creado con IA. Comprobado: los contenidos, el funcionamiento y el tratamiento de los datos."', '"Created with AI. Checked: the content, how it works and how data are handled."'),
        ('"Quien lo reutilice debe saberlo para decidir cuánto puede fiarse de él."', '"Whoever reuses it needs to know this to decide how far to trust it."'),
        ('[["Código", ["AGPL v3", "MIT"], "software libre", 90, 3.8], ["Contenidos", ["CC BY-SA", "CC BY"], "Creative Commons libre", 560, 4.3]]',
         '[["Code", ["AGPL v3", "MIT"], "free software", 90, 3.8], ["Content", ["CC BY-SA", "CC BY"], "free Creative Commons", 560, 4.3]]'),
        ('"Sin licencia, un material no puede reutilizarse con seguridad, aunque esté publicado."', '"Without a licence, a material cannot be safely reused, even if it is published."'),
        ('"Otra persona puede adaptarlo a su aula sin pedir nada a nadie."', '"Someone else can adapt it to their classroom without asking anyone."'),
        ('[[0, "Inicio"], [16, "Proteger al alumnado"], [34, "Construir el material"], [60, "Documentar el trabajo"], [86, "Compartir el material"], [104, "Final"]]',
         '[[0, "Start"], [16, "Protect students"], [34, "Build the material"], [60, "Document the work"], [86, "Share the material"], [104, "End"]]'),
        ('reproduciendo ? "Pausar" : fin ? "Volver a empezar" : "Reproducir";', 'reproduciendo ? "Pause" : fin ? "Start again" : "Play";'),
        ('et + " (barra espaciadora)"', 'et + " (space bar)"'),
        ('silencio ? "Activar el sonido" : "Silenciar"', 'silencio ? "Turn sound on" : "Mute"'),
        ("`${mmss(t)} de ${mmss(TOTAL)}, ${cap}`", "`${mmss(t)} of ${mmss(TOTAL)}, ${cap}`"),
        ("`${capituloEn(t) + 1} de ${CAPITULOS.length}: ${cap}`", "`${capituloEn(t) + 1} of ${CAPITULOS.length}: ${cap}`"),
    ],
    "ca": [
        ("Vibe coding responsable · Zoom infinito", "Vibe coding responsable · Zoom infinit"),
        ('content="Animación de la guía «Vibe coding responsable» en un solo plano: un zoom infinito que entra en el cursor de una conversación con la IA y recorre las diez recomendaciones en cuatro mundos, uno dentro de otro."',
         'content="Animació de la guia «Vibe coding responsable» en un sol pla: un zoom infinit que entra al cursor d\'una conversa amb la IA i recorre les deu recomanacions en quatre mons, l\'un dins de l\'altre."'),
        ("<span>· Zoom infinito</span>", "<span>· Zoom infinit</span>"),
        ("<h1>La guía en un zoom infinito</h1>", "<h1>La guia en un zoom infinit</h1>"),
        ('aria-label="Animación en un solo plano sobre la guía Vibe coding responsable."', 'aria-label="Animació en un sol pla sobre la guia Vibe coding responsable."'),
        ("Reproducir con sonido</button>", "Reprodueix amb so</button>"),
        ('"Parte anterior"', '"Part anterior"'),
        ('aria-label="Reproducir" title="Reproducir (barra espaciadora)"', 'aria-label="Reprodueix" title="Reprodueix (barra d\'espai)"'),
        ('"Parte siguiente"', '"Part següent"'),
        ('aria-label="Posición en la animación"', 'aria-label="Posició a l\'animació"'),
        ('aria-label="Silenciar" title="Silenciar"', 'aria-label="Silencia" title="Silencia"'),
        (". Contenido: <a", ". Contingut: <a"),
        ('<span>Creada con IA (<a href="https://jjdeharo.github.io/miae/?nivel=4" target="_blank" rel="noopener">nivel 4 del MIAE</a>): el autor ha dirigido el trabajo y ha contrastado los textos con la guía.</span>',
         '<span>Creada amb IA (<a href="https://jjdeharo.github.io/miae/?nivel=4" target="_blank" rel="noopener">nivell 4 del MIAE</a>): l\'autor ha dirigit la feina i ha contrastat els textos amb la guia.</span>'),
        ('"› crea una simulación del ciclo del agua"', '"› crea una simulació del cicle de l\'aigua"'),
        ('"VIBE CODING EDUCATIVO"', '"VIBE CODING EDUCATIU"'),
        ('"escribe el código."', '"escriu el codi."'),
        ('"aporta la intención pedagógica"', '"aporta la intenció pedagògica"'),
        ('"y comprueba el resultado."', '"i comprova el resultat."'),
        ('"Quien publica el material responde de él,"', '"Qui publica el material en respon,"'),
        ('"aunque el código sea de la IA."', '"encara que el codi sigui de la IA."'),
        ('"recomendaciones", A(12.9', '"recomanacions", A(12.9'),
        ('"antes de publicar"', '"abans de publicar"'),
        ('"Vibe coding ético"', '"Vibe coding ètic"'),
        ('"Vibe coding educativo responsable: materiales…"', '"Vibe coding educatiu responsable: materials…"'),
        ('[["seguros", "para el alumnado,"], ["accesibles,", ""], ["duraderos,", ""], ["transparentes", "sobre cómo se hicieron"], ["y libres", "para que otras personas los reutilicen."]]',
         '[["segurs", "per a l\'alumnat,"], ["accessibles,", ""], ["duradors,", ""], ["transparents", "sobre com es van fer"], ["i lliures", "perquè altres persones els reutilitzin."]]'),
        ("Para empezar:</b> dar a la IA el archivo de instrucciones y, al terminar, pedirle la evaluación VCER. La revisión del contenido corresponde a la persona.",
         "Per començar:</b> donar a la IA el fitxer d'instruccions i, en acabar, demanar-li l'avaluació VCER. La revisió del contingut correspon a la persona."),
        ("Iconos: Lucide (ISC y MIT) · Tipografía: Atkinson Hyperlegible (OFL)<br>Animación, música y sonido generados con IA.",
         "Icones: Lucide (ISC i MIT) · Tipografia: Atkinson Hyperlegible (OFL)<br>Animació, música i so generats amb IA."),
        ('fase(N1, 1, "Proteger", "al alumnado"', 'fase(N1, 1, "Protegir", "l\'alumnat"'),
        ('fase(N3, 3, "Documentar", "el trabajo"', 'fase(N3, 3, "Documentar", "la feina"'),
        ('"Revisar el contenido sin delegarlo en la IA"', '"Revisar el contingut sense delegar-lo a la IA"'),
        ('"No enviar datos personales a servicios ajenos al centro"', '"No enviar dades personals a serveis aliens al centre"'),
        ('"Entender qué hace el material"', '"Entendre què fa el material"'),
        ('"No depender de servicios que pueden desaparecer"', '"No dependre de serveis que poden desaparèixer"'),
        ('"Hacerlo accesible a cualquier persona"', '"Fer-lo accessible a qualsevol persona"'),
        ('"Citar la autoría de lo que se toma de otras personas"', '"Citar l\'autoria del que es pren d\'altres persones"'),
        ('"Guardar el rastro de cómo se hizo"', '"Guardar el rastre de com es va fer"'),
        ('"Declarar el uso de IA y lo que se ha comprobado"', '"Declarar l\'ús d\'IA i el que s\'ha comprovat"'),
        ('"Publicar con una licencia libre a la vista"', '"Publicar amb una llicència lliure a la vista"'),
        ('"Ofrecer el código para que otras personas lo adapten"', '"Oferir el codi perquè altres persones l\'adaptin"'),
        (">PREGUNTA DEL CUESTIONARIO<", ">PREGUNTA DEL QÜESTIONARI<"),
        (">El agua hierve a 90 °C a nivel del mar.<", ">L'aigua bull a 90 °C al nivell del mar.<"),
        ("} Verdadero`", "} Vertader`"),
        ('"La IA puede equivocarse con total naturalidad."', '"La IA es pot equivocar amb tota naturalitat."'),
        ('"La responsabilidad de lo que se enseña es de la persona que lo publica."', '"La responsabilitat del que s\'ensenya és de la persona que ho publica."'),
        ('"La forma más sencilla de cumplir: que el material no pida datos."', '"La manera més senzilla de complir: que el material no demani dades."'),
        ("<p>servicio ajeno al centro</p>", "<p>servei aliè al centre</p>"),
        ('"Los datos, solo en el dispositivo."', '"Les dades, només al dispositiu."'),
        ('["nombre", "notas", "voz", "imagen"]', '["nom", "notes", "veu", "imatge"]'),
        ("</span> comprobar(respuesta) {", "</span> comprova(resposta) {"),
        ("</span> bien = respuesta === solucion;", "</span> be = resposta === solucio;"),
        ('mostrar(bien ? <span style="color:#f5c542">"¡Correcto!"</span> : <span style="color:#f5c542">"Revisa"</span>);',
         'mostra(be ? <span style="color:#f5c542">"Correcte!"</span> : <span style="color:#f5c542">"Revisa"</span>);'),
        ('"progreso"</span>, nivel);', '"progres"</span>, nivell);'),
        ("// sin conexiones a servidores externos", "// sense connexions a servidors externs"),
        ('[["Qué hace", "comprueba las respuestas", 3.9, 452], ["Qué guarda", "el progreso, en el dispositivo", 4.5, 572], ["Con qué se comunica", "con ningún servidor externo", 5.1, 692]]',
         '[["Què fa", "comprova les respostes", 3.9, 452], ["Què guarda", "el progrés, al dispositiu", 4.5, 572], ["Amb què es comunica", "amb cap servidor extern", 5.1, 692]]'),
        ('"No hace falta saber programar: basta con pedir a la IA que lo explique en lenguaje llano y comprobarlo al usarlo."',
         '"No cal saber programar: n\'hi ha prou de demanar a la IA que ho expliqui en llenguatge planer i comprovar-ho en fer-lo servir."'),
        (">la plataforma donde se creó<", ">la plataforma on es va crear<"),
        ("} enlace compartido`", "} enllaç compartit`"),
        ("} enlace roto`", "} enllaç trencat`"),
        ('"copia del código"', '"còpia del codi"'),
        ('"El enlace compartido dura lo que la empresa decida."', '"L\'enllaç compartit dura el que l\'empresa decideixi."'),
        ('"Por eso, una copia del código en el propio ordenador."', '"Per això, una còpia del codi a l\'ordinador propi."'),
        (">sin ratón<", ">sense ratolí<"),
        ("} Correcto</div>", "} Correcte</div>"),
        (">sin depender del color<", ">sense dependre del color<"),
        (">Ciclo del agua</b><br>Evaporación, condensación y precipitación.<", ">Cicle de l'aigua</b><br>Evaporació, condensació i precipitació.<"),
        (">en una pantalla pequeña<", ">en una pantalla petita<"),
        ('"Pedir a la IA, desde el principio, que siga las pautas de accesibilidad."', '"Demanar a la IA, des del principi, que segueixi les pautes d\'accessibilitat."'),
        ('[["imagen", "imagen"], ["musica", "sonido"], [null, "tipografía"]]', '[["imagen", "imatge"], ["musica", "so"], [null, "tipografia"]]'),
        ('"<b>Autoría</b><br><b>Procedencia</b><br><b>Licencia</b>"', '"<b>Autoria</b><br><b>Procedència</b><br><b>Llicència</b>"'),
        ('"Tienen autoría y licencia, aunque los haya colocado la IA."', '"Tenen autoria i llicència, encara que els hi hagi posat la IA."'),
        ('[["Los datos se guardan solo en el dispositivo.", "Porque son datos del alumnado."],\n ["Iconos de una biblioteca con licencia libre.", "Porque se pueden reutilizar y citar."],\n ["Sin cuentas de usuario.", "Porque así el alumnado no tiene que registrarse."]]',
         '[["Les dades es guarden només al dispositiu.", "Perquè són dades de l\'alumnat."],\n ["Icones d\'una biblioteca amb llicència lliure.", "Perquè es poden reutilitzar i citar."],\n ["Sense comptes d\'usuari.", "Perquè així l\'alumnat no s\'ha de registrar."]]'),
        ('"Lo redacta la propia IA al terminar cada sesión; la persona lo revisa."', '"El redacta la mateixa IA en acabar cada sessió; la persona el revisa."'),
        ('"Creado con IA. Comprobado: los contenidos, el funcionamiento y el tratamiento de los datos."', '"Creat amb IA. Comprovat: els continguts, el funcionament i el tractament de les dades."'),
        ('"Quien lo reutilice debe saberlo para decidir cuánto puede fiarse de él."', '"Qui el reutilitzi ho ha de saber per decidir fins a quin punt se\'n pot refiar."'),
        ('[["Código", ["AGPL v3", "MIT"], "software libre", 90, 3.8], ["Contenidos", ["CC BY-SA", "CC BY"], "Creative Commons libre", 560, 4.3]]',
         '[["Codi", ["AGPL v3", "MIT"], "programari lliure", 90, 3.8], ["Continguts", ["CC BY-SA", "CC BY"], "Creative Commons lliure", 560, 4.3]]'),
        ('"Sin licencia, un material no puede reutilizarse con seguridad, aunque esté publicado."', '"Sense llicència, un material no es pot reutilitzar amb seguretat, encara que estigui publicat."'),
        ('"Otra persona puede adaptarlo a su aula sin pedir nada a nadie."', '"Una altra persona el pot adaptar a la seva aula sense demanar res a ningú."'),
        ('[[0, "Inicio"], [16, "Proteger al alumnado"], [34, "Construir el material"], [60, "Documentar el trabajo"], [86, "Compartir el material"], [104, "Final"]]',
         '[[0, "Inici"], [16, "Protegir l\'alumnat"], [34, "Construir el material"], [60, "Documentar la feina"], [86, "Compartir el material"], [104, "Final"]]'),
        ('reproduciendo ? "Pausar" : fin ? "Volver a empezar" : "Reproducir";', 'reproduciendo ? "Pausa" : fin ? "Torna a començar" : "Reprodueix";'),
        ('et + " (barra espaciadora)"', 'et + " (barra d\'espai)"'),
        ('silencio ? "Activar el sonido" : "Silenciar"', 'silencio ? "Activa el so" : "Silencia"'),
    ],
    "gl": [
        ('content="Animación de la guía «Vibe coding responsable» en un solo plano: un zoom infinito que entra en el cursor de una conversación con la IA y recorre las diez recomendaciones en cuatro mundos, uno dentro de otro."',
         'content="Animación da guía «Vibe coding responsable» nun só plano: un zoom infinito que entra no cursor dunha conversa coa IA e percorre as dez recomendacións en catro mundos, un dentro doutro."'),
        ("<h1>La guía en un zoom infinito</h1>", "<h1>A guía nun zoom infinito</h1>"),
        ('aria-label="Animación en un solo plano sobre la guía Vibe coding responsable."', 'aria-label="Animación nun só plano sobre a guía Vibe coding responsable."'),
        ("Reproducir con sonido</button>", "Reproducir con son</button>"),
        ('"Parte siguiente"', '"Parte seguinte"'),
        ('aria-label="Posición en la animación"', 'aria-label="Posición na animación"'),
        (". Contenido: <a", ". Contido: <a"),
        ('<span>Creada con IA (<a href="https://jjdeharo.github.io/miae/?nivel=4" target="_blank" rel="noopener">nivel 4 del MIAE</a>): el autor ha dirigido el trabajo y ha contrastado los textos con la guía.</span>',
         '<span>Creada con IA (<a href="https://jjdeharo.github.io/miae/?nivel=4" target="_blank" rel="noopener">nivel 4 do MIAE</a>): o autor dirixiu o traballo e contrastou os textos coa guía.</span>'),
        ('"› crea una simulación del ciclo del agua"', '"› crea unha simulación do ciclo da auga"'),
        ('"La IA", A(4.1', '"A IA", A(4.1'),
        ('"escribe el código."', '"escribe o código."'),
        ('"La persona", A(7.0', '"A persoa", A(7.0'),
        ('"aporta la intención pedagógica"', '"achega a intención pedagóxica"'),
        ('"y comprueba el resultado."', '"e comproba o resultado."'),
        ('"Quien publica el material responde de él,"', '"Quen publica o material responde del,"'),
        ('"aunque el código sea de la IA."', '"aínda que o código sexa da IA."'),
        ('"recomendaciones", A(12.9', '"recomendacións", A(12.9'),
        ('"Vibe coding educativo responsable: materiales…"', '"Vibe coding educativo responsable: materiais…"'),
        ('[["seguros", "para el alumnado,"], ["accesibles,", ""], ["duraderos,", ""], ["transparentes", "sobre cómo se hicieron"], ["y libres", "para que otras personas los reutilicen."]]',
         '[["seguros", "para o alumnado,"], ["accesibles,", ""], ["duradeiros,", ""], ["transparentes", "sobre como se fixeron"], ["e libres", "para que outras persoas os reutilicen."]]'),
        ("Para empezar:</b> dar a la IA el archivo de instrucciones y, al terminar, pedirle la evaluación VCER. La revisión del contenido corresponde a la persona.",
         "Para comezar:</b> darlle á IA o ficheiro de instrucións e, ao rematar, pedirlle a avaliación VCER. A revisión do contido correspóndelle á persoa."),
        ("Iconos: Lucide (ISC y MIT) · Tipografía: Atkinson Hyperlegible (OFL)<br>Animación, música y sonido generados con IA.",
         "Iconas: Lucide (ISC e MIT) · Tipografía: Atkinson Hyperlegible (OFL)<br>Animación, música e son xerados con IA."),
        ('fase(N1, 1, "Proteger", "al alumnado"', 'fase(N1, 1, "Protexer", "o alumnado"'),
        ('fase(N2, 2, "Construir", "el material"', 'fase(N2, 2, "Construír", "o material"'),
        ('fase(N3, 3, "Documentar", "el trabajo"', 'fase(N3, 3, "Documentar", "o traballo"'),
        ('fase(N4, 4, "Compartir", "el material"', 'fase(N4, 4, "Compartir", "o material"'),
        ('"Revisar el contenido sin delegarlo en la IA"', '"Revisar o contido sen delegalo na IA"'),
        ('"No enviar datos personales a servicios ajenos al centro"', '"Non enviar datos persoais a servizos alleos ao centro"'),
        ('"Entender qué hace el material"', '"Entender que fai o material"'),
        ('"No depender de servicios que pueden desaparecer"', '"Non depender de servizos que poden desaparecer"'),
        ('"Hacerlo accesible a cualquier persona"', '"Facelo accesible a calquera persoa"'),
        ('"Citar la autoría de lo que se toma de otras personas"', '"Citar a autoría do que se toma doutras persoas"'),
        ('"Guardar el rastro de cómo se hizo"', '"Gardar o rastro de como se fixo"'),
        ('"Declarar el uso de IA y lo que se ha comprobado"', '"Declarar o uso de IA e o que se comprobou"'),
        ('"Publicar con una licencia libre a la vista"', '"Publicar cunha licenza libre á vista"'),
        ('"Ofrecer el código para que otras personas lo adapten"', '"Ofrecer o código para que outras persoas o adapten"'),
        (">PREGUNTA DEL CUESTIONARIO<", ">PREGUNTA DO CUESTIONARIO<"),
        (">El agua hierve a 90 °C a nivel del mar.<", ">A auga ferve a 90 °C ao nivel do mar.<"),
        ("} Verdadero`", "} Verdadeiro`"),
        ("} Error`", "} Erro`"),
        ('"La IA puede equivocarse con total naturalidad."', '"A IA pode equivocarse con total naturalidade."'),
        ('"La responsabilidad de lo que se enseña es de la persona que lo publica."', '"A responsabilidade do que se ensina é da persoa que o publica."'),
        ('"La forma más sencilla de cumplir: que el material no pida datos."', '"A forma máis sinxela de cumprir: que o material non pida datos."'),
        ("<p>servicio ajeno al centro</p>", "<p>servizo alleo ao centro</p>"),
        ('"Los datos, solo en el dispositivo."', '"Os datos, só no dispositivo."'),
        ('["nombre", "notas", "voz", "imagen"]', '["nome", "notas", "voz", "imaxe"]'),
        ("</span> bien = respuesta === solucion;", "</span> ben = resposta === solucion;"),
        ("</span> comprobar(respuesta) {", "</span> comprobar(resposta) {"),
        ('mostrar(bien ? <span style="color:#f5c542">"¡Correcto!"</span> : <span style="color:#f5c542">"Revisa"</span>);',
         'amosar(ben ? <span style="color:#f5c542">"Correcto!"</span> : <span style="color:#f5c542">"Revisa"</span>);'),
        ("// sin conexiones a servidores externos", "// sen conexións a servidores externos"),
        ('[["Qué hace", "comprueba las respuestas", 3.9, 452], ["Qué guarda", "el progreso, en el dispositivo", 4.5, 572], ["Con qué se comunica", "con ningún servidor externo", 5.1, 692]]',
         '[["Que fai", "comproba as respostas", 3.9, 452], ["Que garda", "o progreso, no dispositivo", 4.5, 572], ["Con que se comunica", "con ningún servidor externo", 5.1, 692]]'),
        ('"No hace falta saber programar: basta con pedir a la IA que lo explique en lenguaje llano y comprobarlo al usarlo."',
         '"Non fai falta saber programar: abonda con pedirlle á IA que o explique en linguaxe sinxela e comprobalo ao usalo."'),
        (">la plataforma donde se creó<", ">a plataforma onde se creou<"),
        ("} enlace compartido`", "} ligazón compartida`"),
        ("} enlace roto`", "} ligazón rota`"),
        ('"copia del código"', '"copia do código"'),
        ('"El enlace compartido dura lo que la empresa decida."', '"A ligazón compartida dura o que a empresa decida."'),
        ('"Por eso, una copia del código en el propio ordenador."', '"Por iso, unha copia do código no propio ordenador."'),
        (">sin ratón<", ">sen rato<"),
        ("} Error</div>", "} Erro</div>"),
        (">sin depender del color<", ">sen depender da cor<"),
        (">Ciclo del agua</b><br>Evaporación, condensación y precipitación.<", ">Ciclo da auga</b><br>Evaporación, condensación e precipitación.<"),
        (">en una pantalla pequeña<", ">nunha pantalla pequena<"),
        ('"Pedir a la IA, desde el principio, que siga las pautas de accesibilidad."', '"Pedirlle á IA, desde o principio, que siga as pautas de accesibilidade."'),
        ('[["imagen", "imagen"], ["musica", "sonido"], [null, "tipografía"]]', '[["imagen", "imaxe"], ["musica", "son"], [null, "tipografía"]]'),
        ('"<b>Autoría</b><br><b>Procedencia</b><br><b>Licencia</b>"', '"<b>Autoría</b><br><b>Procedencia</b><br><b>Licenza</b>"'),
        ('"Tienen autoría y licencia, aunque los haya colocado la IA."', '"Teñen autoría e licenza, aínda que os colocase a IA."'),
        ('[["Los datos se guardan solo en el dispositivo.", "Porque son datos del alumnado."],\n ["Iconos de una biblioteca con licencia libre.", "Porque se pueden reutilizar y citar."],\n ["Sin cuentas de usuario.", "Porque así el alumnado no tiene que registrarse."]]',
         '[["Os datos gárdanse só no dispositivo.", "Porque son datos do alumnado."],\n ["Iconas dunha biblioteca con licenza libre.", "Porque se poden reutilizar e citar."],\n ["Sen contas de usuario.", "Porque así o alumnado non ten que rexistrarse."]]'),
        ('"Lo redacta la propia IA al terminar cada sesión; la persona lo revisa."', '"Redáctao a propia IA ao rematar cada sesión; a persoa revísao."'),
        ('"Creado con IA. Comprobado: los contenidos, el funcionamiento y el tratamiento de los datos."', '"Creado con IA. Comprobado: os contidos, o funcionamento e o tratamento dos datos."'),
        ('"Quien lo reutilice debe saberlo para decidir cuánto puede fiarse de él."', '"Quen o reutilice debe sabelo para decidir canto se pode fiar del."'),
        ('[["Código", ["AGPL v3", "MIT"], "software libre", 90, 3.8], ["Contenidos", ["CC BY-SA", "CC BY"], "Creative Commons libre", 560, 4.3]]',
         '[["Código", ["AGPL v3", "MIT"], "software libre", 90, 3.8], ["Contidos", ["CC BY-SA", "CC BY"], "Creative Commons libre", 560, 4.3]]'),
        ('"Sin licencia, un material no puede reutilizarse con seguridad, aunque esté publicado."', '"Sen licenza, un material non se pode reutilizar con seguridade, aínda que estea publicado."'),
        ('"Otra persona puede adaptarlo a su aula sin pedir nada a nadie."', '"Outra persoa pode adaptalo á súa aula sen lle pedir nada a ninguén."'),
        ('[[0, "Inicio"], [16, "Proteger al alumnado"], [34, "Construir el material"], [60, "Documentar el trabajo"], [86, "Compartir el material"], [104, "Final"]]',
         '[[0, "Inicio"], [16, "Protexer o alumnado"], [34, "Construír o material"], [60, "Documentar o traballo"], [86, "Compartir o material"], [104, "Final"]]'),
        ('fin ? "Volver a empezar" :', 'fin ? "Volver comezar" :'),
        ('silencio ? "Activar el sonido" : "Silenciar"', 'silencio ? "Activar o son" : "Silenciar"'),
    ],
    "eu": [
        ("Vibe coding responsable · Zoom infinito", "Vibe coding arduratsua · Zoom infinitua"),
        ('content="Animación de la guía «Vibe coding responsable» en un solo plano: un zoom infinito que entra en el cursor de una conversación con la IA y recorre las diez recomendaciones en cuatro mundos, uno dentro de otro."',
         'content="«Vibe coding arduratsua» gidaren animazioa plano bakarrean: IArekiko elkarrizketa baten kurtsorean sartzen den zoom infinitu bat, hamar gomendioak lau mundutan zeharkatzen dituena, bata bestearen barruan."'),
        ('alt="">Vibe coding responsable</a>', 'alt="">Vibe coding arduratsua</a>'),
        ("<span>· Zoom infinito</span>", "<span>· Zoom infinitua</span>"),
        ("<h1>La guía en un zoom infinito</h1>", "<h1>Gida zoom infinitu batean</h1>"),
        ('aria-label="Animación en un solo plano sobre la guía Vibe coding responsable."', 'aria-label="Vibe coding arduratsua gidari buruzko animazioa, plano bakarrean."'),
        ("Reproducir con sonido</button>", "Erreproduzitu soinuarekin</button>"),
        ('"Parte anterior"', '"Aurreko zatia"'),
        ('aria-label="Reproducir" title="Reproducir (barra espaciadora)"', 'aria-label="Erreproduzitu" title="Erreproduzitu (zuriune-barra)"'),
        ('"Parte siguiente"', '"Hurrengo zatia"'),
        ('aria-label="Posición en la animación"', 'aria-label="Animazioko posizioa"'),
        ('aria-label="Silenciar" title="Silenciar"', 'aria-label="Isilarazi" title="Isilarazi"'),
        (". Contenido: <a", ". Edukia: <a"),
        ('<span>Creada con IA (<a href="https://jjdeharo.github.io/miae/?nivel=4" target="_blank" rel="noopener">nivel 4 del MIAE</a>): el autor ha dirigido el trabajo y ha contrastado los textos con la guía.</span>',
         '<span>IArekin sortua (<a href="https://jjdeharo.github.io/miae/?nivel=4" target="_blank" rel="noopener">MIAEren 4. maila</a>): egileak lana zuzendu du eta testuak gidarekin kontrastatu ditu.</span>'),
        ('"› crea una simulación del ciclo del agua"', '"› sortu uraren zikloaren simulazio bat"'),
        ('"VIBE CODING EDUCATIVO"', '"VIBE CODING HEZITZAILEA"'),
        ('"La IA", A(4.1', '"IAk", A(4.1'),
        ('"escribe el código."', '"kodea idazten du."'),
        ('"La persona", A(7.0', '"Pertsonak", A(7.0'),
        ('"aporta la intención pedagógica"', '"asmo pedagogikoa jartzen du"'),
        ('"y comprueba el resultado."', '"eta emaitza egiaztatzen du."'),
        ('"Quien publica el material responde de él,"', '"Materiala argitaratzen duena da haren erantzule,"'),
        ('"aunque el código sea de la IA."', '"kodea IArena izan arren."'),
        ('"recomendaciones", A(12.9', '"gomendio", A(12.9'),
        ('"antes de publicar"', '"argitaratu aurretik"'),
        ('"responsable", A(109.45', '"arduratsua", A(109.45'),
        ('"Vibe coding ético"', '"Vibe coding etikoa"'),
        ('"Vibe coding educativo responsable: materiales…"', '"Vibe coding hezitzaile arduratsua: materialak…"'),
        ('[["seguros", "para el alumnado,"], ["accesibles,", ""], ["duraderos,", ""], ["transparentes", "sobre cómo se hicieron"], ["y libres", "para que otras personas los reutilicen."]]',
         '[["seguruak", "ikasleentzat,"], ["irisgarriak,", ""], ["iraunkorrak,", ""], ["gardenak", "nola egin ziren azaltzean"], ["eta libreak", "beste batzuek berrerabil ditzaten."]]'),
        ("Para empezar:</b> dar a la IA el archivo de instrucciones y, al terminar, pedirle la evaluación VCER. La revisión del contenido corresponde a la persona.",
         "Hasteko:</b> IAri jarraibideen fitxategia eman eta, amaitzean, VCER ebaluazioa eskatu. Edukiaren berrikuspena pertsonari dagokio."),
        ("Iconos: Lucide (ISC y MIT) · Tipografía: Atkinson Hyperlegible (OFL)<br>Animación, música y sonido generados con IA.",
         "Ikonoak: Lucide (ISC eta MIT) · Tipografia: Atkinson Hyperlegible (OFL)<br>Animazioa, musika eta soinua IArekin sortuak."),
        ('fase(N1, 1, "Proteger", "al alumnado"', 'fase(N1, 1, "Ikasleak", "babestu"'),
        ('fase(N2, 2, "Construir", "el material"', 'fase(N2, 2, "Materiala", "eraiki"'),
        ('fase(N3, 3, "Documentar", "el trabajo"', 'fase(N3, 3, "Lana", "dokumentatu"'),
        ('fase(N4, 4, "Compartir", "el material"', 'fase(N4, 4, "Materiala", "partekatu"'),
        ("`FASE ${numero} DE 4`", "`${numero}. FASEA / 4`"),
        ('"Revisar el contenido sin delegarlo en la IA"', '"Edukia berrikustea, IAren esku utzi gabe"'),
        ('"No enviar datos personales a servicios ajenos al centro"', '"Datu pertsonalak ez bidaltzea ikastetxetik kanpoko zerbitzuetara"'),
        ('"Entender qué hace el material"', '"Materialak zer egiten duen ulertzea"'),
        ('"No depender de servicios que pueden desaparecer"', '"Desager daitezkeen zerbitzuen mende ez egotea"'),
        ('"Hacerlo accesible a cualquier persona"', '"Edonorentzat irisgarri egitea"'),
        ('"Citar la autoría de lo que se toma de otras personas"', '"Besteengandik hartutakoaren egiletza aipatzea"'),
        ('"Guardar el rastro de cómo se hizo"', '"Nola egin zen arrastoa gordetzea"'),
        ('"Declarar el uso de IA y lo que se ha comprobado"', '"IAren erabilera eta egiaztatutakoa adieraztea"'),
        ('"Publicar con una licencia libre a la vista"', '"Lizentzia libre batekin argitaratzea, agerian"'),
        ('"Ofrecer el código para que otras personas lo adapten"', '"Kodea eskaintzea, besteek egoki dezaten"'),
        (">PREGUNTA DEL CUESTIONARIO<", ">GALDETEGIKO GALDERA<"),
        (">El agua hierve a 90 °C a nivel del mar.<", ">Ura 90 °C-tan irakiten da itsas mailan.<"),
        ("} Verdadero`", "} Egia`"),
        ("} Error`", "} Akatsa`"),
        ('"La IA puede equivocarse con total naturalidad."', '"IA erabateko naturaltasunez oker daiteke."'),
        ('"La responsabilidad de lo que se enseña es de la persona que lo publica."', '"Irakasten denaren erantzukizuna argitaratzen duen pertsonarena da."'),
        ('"La forma más sencilla de cumplir: que el material no pida datos."', '"Betetzeko modurik errazena: materialak daturik ez eskatzea."'),
        ("<p>servicio ajeno al centro</p>", "<p>ikastetxetik kanpoko zerbitzua</p>"),
        ('"Los datos, solo en el dispositivo."', '"Datuak, gailuan bakarrik."'),
        ('["nombre", "notas", "voz", "imagen"]', '["izena", "notak", "ahotsa", "irudia"]'),
        ("</span> comprobar(respuesta) {", "</span> egiaztatu(erantzuna) {"),
        ("</span> bien = respuesta === solucion;", "</span> ondo = erantzuna === soluzioa;"),
        ('mostrar(bien ? <span style="color:#f5c542">"¡Correcto!"</span> : <span style="color:#f5c542">"Revisa"</span>);',
         'erakutsi(ondo ? <span style="color:#f5c542">"Zuzena!"</span> : <span style="color:#f5c542">"Berrikusi"</span>);'),
        ('"progreso"</span>, nivel);', '"egoera"</span>, maila);'),
        ("// sin conexiones a servidores externos", "// kanpoko zerbitzaririk gabe"),
        ('[["Qué hace", "comprueba las respuestas", 3.9, 452], ["Qué guarda", "el progreso, en el dispositivo", 4.5, 572], ["Con qué se comunica", "con ningún servidor externo", 5.1, 692]]',
         '[["Zer egiten du", "erantzunak egiaztatzen ditu", 3.9, 452], ["Zer gordetzen du", "aurrerapena, gailuan", 4.5, 572], ["Konexioak", "kanpoko zerbitzaririk ez", 5.1, 692]]'),
        ('"No hace falta saber programar: basta con pedir a la IA que lo explique en lenguaje llano y comprobarlo al usarlo."',
         '"Ez da programatzen jakin behar: nahikoa da IAri hizkera arruntean azal dezala eskatzea eta erabiltzean egiaztatzea."'),
        (">la plataforma donde se creó<", ">sortu zen plataforma<"),
        ("} enlace compartido`", "} partekatutako esteka`"),
        ("} enlace roto`", "} esteka hautsia`"),
        ('"copia del código"', '"kodearen kopia"'),
        ('"El enlace compartido dura lo que la empresa decida."', '"Partekatutako estekak enpresak erabakitzen duen bitartean irauten du."'),
        ('"Por eso, una copia del código en el propio ordenador."', '"Horregatik, kodearen kopia bat norberaren ordenagailuan."'),
        (">sin ratón<", ">sagurik gabe<"),
        ("} Correcto</div>", "} Zuzena</div>"),
        ("} Error</div>", "} Akatsa</div>"),
        (">sin depender del color<", ">kolorearen mende egon gabe<"),
        (">Ciclo del agua</b><br>Evaporación, condensación y precipitación.<", ">Uraren zikloa</b><br>Lurruntzea, kondentsazioa eta prezipitazioa.<"),
        (">en una pantalla pequeña<", ">pantaila txiki batean<"),
        ('"Pedir a la IA, desde el principio, que siga las pautas de accesibilidad."', '"IAri hasieratik eskatzea irisgarritasun-jarraibideak bete ditzala."'),
        ('[["imagen", "imagen"], ["musica", "sonido"], [null, "tipografía"]]', '[["imagen", "irudia"], ["musica", "soinua"], [null, "tipografia"]]'),
        ('"<b>Autoría</b><br><b>Procedencia</b><br><b>Licencia</b>"', '"<b>Egilea</b><br><b>Jatorria</b><br><b>Lizentzia</b>"'),
        ('"Tienen autoría y licencia, aunque los haya colocado la IA."', '"Egilea eta lizentzia dituzte, IAk jarri baditu ere."'),
        ('[["Los datos se guardan solo en el dispositivo.", "Porque son datos del alumnado."],\n ["Iconos de una biblioteca con licencia libre.", "Porque se pueden reutilizar y citar."],\n ["Sin cuentas de usuario.", "Porque así el alumnado no tiene que registrarse."]]',
         '[["Datuak gailuan bakarrik gordetzen dira.", "Ikasleen datuak direlako."],\n ["Lizentzia libreko liburutegi bateko ikonoak.", "Berrerabili eta aipa daitezkeelako."],\n ["Erabiltzaile-konturik gabe.", "Horrela ikasleek ez dutelako erregistratu behar."]]'),
        ('"Lo redacta la propia IA al terminar cada sesión; la persona lo revisa."', '"IAk berak idazten du saio bakoitzaren amaieran; pertsonak berrikusten du."'),
        ('"Creado con IA. Comprobado: los contenidos, el funcionamiento y el tratamiento de los datos."', '"IArekin sortua. Egiaztatua: edukiak, funtzionamendua eta datuen tratamendua."'),
        ('"Quien lo reutilice debe saberlo para decidir cuánto puede fiarse de él."', '"Berrerabiltzen duenak jakin behar du, zenbateraino fida daitekeen erabakitzeko."'),
        ('[["Código", ["AGPL v3", "MIT"], "software libre", 90, 3.8], ["Contenidos", ["CC BY-SA", "CC BY"], "Creative Commons libre", 560, 4.3]]',
         '[["Kodea", ["AGPL v3", "MIT"], "software librea", 90, 3.8], ["Edukiak", ["CC BY-SA", "CC BY"], "Creative Commons librea", 560, 4.3]]'),
        ('"Sin licencia, un material no puede reutilizarse con seguridad, aunque esté publicado."', '"Lizentziarik gabe, material bat ezin da segurtasunez berrerabili, argitaratuta egon arren."'),
        ('"Otra persona puede adaptarlo a su aula sin pedir nada a nadie."', '"Beste pertsona batek bere gelara egoki dezake inori ezer eskatu gabe."'),
        ('[[0, "Inicio"], [16, "Proteger al alumnado"], [34, "Construir el material"], [60, "Documentar el trabajo"], [86, "Compartir el material"], [104, "Final"]]',
         '[[0, "Hasiera"], [16, "Ikasleak babestu"], [34, "Materiala eraiki"], [60, "Lana dokumentatu"], [86, "Materiala partekatu"], [104, "Amaiera"]]'),
        ('reproduciendo ? "Pausar" : fin ? "Volver a empezar" : "Reproducir";', 'reproduciendo ? "Pausatu" : fin ? "Berriro hasi" : "Erreproduzitu";'),
        ('et + " (barra espaciadora)"', 'et + " (zuriune-barra)"'),
        ('silencio ? "Activar el sonido" : "Silenciar"', 'silencio ? "Soinua aktibatu" : "Isilarazi"'),
        ("`${mmss(t)} de ${mmss(TOTAL)}, ${cap}`", "`${mmss(t)} / ${mmss(TOTAL)}, ${cap}`"),
        ("`${capituloEn(t) + 1} de ${CAPITULOS.length}: ${cap}`", "`${capituloEn(t) + 1} / ${CAPITULOS.length}: ${cap}`"),
    ],
}


def generar(idioma):
    texto = (AQUI / "zoom.es.html").read_text(encoding="utf-8")
    faltan = []
    for viejo, nuevo in comunes(idioma) + TEXTOS[idioma]:
        if viejo not in texto:
            faltan.append(viejo)
        texto = texto.replace(viejo, nuevo)
    if faltan:
        raise SystemExit(f"{idioma}: textos que ya no están en zoom.es.html:\n  " + "\n  ".join(f[:90] for f in faltan))
    destino = AQUI / f"zoom.{idioma}.html"
    destino.write_text(texto, encoding="utf-8")
    print(destino.name)


if __name__ == "__main__":
    for idioma in sys.argv[1:] or list(TEXTOS):
        generar(idioma)
